### ISSUE TITLE
Cell's identifier name

### ISSUE THREAD

**Issue by stealdre** [malcommac/FlowKit#11]
Hi,

I have a simple code like the demo example to try this library. However, it doesn't work with me.
When I reload the tableView, nothing happens...

Here is my code: 

`viewDidLoad()`

```swift
let userAdpt = TableAdapter<InterestingUser,InterestingUsersTableViewCell>()

userAdpt.on.dequeue = { ctx in
 ctx.cell?.textLabel?.text = ctx.model.firstName
 ctx.cell?.detailTextLabel?.text = ctx.model.uid
}

userAdpt.on.tap = { ctx in
 print("Tapped on user \(ctx.model.identifier)")
 return .deselectAnimated
}

tableView.director.register(adapter: userAdpt)
tableView.director.rowHeight = .fixed(height: 100)

self.tableView.director.reloadData(after: { _ in
  self.tableView.director.firstSection()?.add(models: self.interestingUsers, at: 0)
  return TableReloadAnimations.default()
})
```

[EDIT]

```
//MARK: TableAdaterProtocolFunctions Protocol
	
	func _instanceCell(in table: UITableView, at indexPath: IndexPath?) -> UITableViewCell {
		guard let indexPath = indexPath else {
			let castedCell = self.cellClass as! UITableViewCell.Type
			let cellInstance = castedCell.init()
			return cellInstance
		}
		return table.dequeueReusableCell(withIdentifier: C.reuseIdentifier, for: indexPath)
	}
```

This function makes the app crash with the well known "must register a nib or a class for the identifier or connect a prototype cell in a storyboard"

Thanks in advance four your help.

**Comment by malcommac** [comment]
Hi, is the `InterestingUsersTableViewCell` has `InterestingUsersTableViewCell` as identifier?
Cell's identifier must be the same name of the class itself (you can change it if you want but you should implement your own `reuseIdentifier` of the `CellProtocol` and usually there is no reason to do it).
