### ISSUE TITLE
FlowKit core. Comparing models 

### ISSUE THREAD

**Issue by crabman448** [malcommac/FlowKit#13]
Does FlowKit uses only modelID to compare models for equality?
If so, then modelID should not return hashValue, right? Because as far as I understand there can be collisions when using `hashValue`. 
And documentation also says this:
`Hash values are not guaranteed to be equal across different executions of your program.`
So maybe models should conform to Equatable protocol?

Thanks!

**Comment by malcommac** [comment]
Cannot be conform to `Equatable` because it has a `Self` associated and cannot be generic.
What kind of problem have you found for hash values between executions? Table are reloaded and not saved on disk. Can you explain it better? thanks!

**Comment by crabman448** [comment]
Now I don’t have any problems. I’m trying to clarify some ideas :)
As far as I understand hashValues can have some collisions in rare situations, right?
If so, then is it safe to return hashValue in the modelID?
And another point to clarify: is modelID is used to uniquely indenting model across other modes?

**Comment by twof** [comment]
It would not be safe to return hash values as `modelID` because collisions are certainly possible. 

> And another point to clarify: is modelID is used to uniquely indenting model across other models?

I'm also curious about this.

**Comment by malcommac** [comment]
The point I need to fix is how to check if two models are equals; this stuff is used to evaluate the difference between two states of the datasource and animate rows/cell accordingly.
Currently I've not finalized the API of the project so I'm opened to get a better solution for this stuff. Any idea?

**Comment by twof** [comment]
I don't think it's realistic to expect `modelID` to be unique across all models with registered adapters, so one thing you could do is check for type equivalence of models first, then `modelID` equivalence. 

Another option is to do what [DifferenceKit](https://github.com/ra1028/DifferenceKit) does and require that users provide `func isContentEqual(to:) -> Bool` in addition to an ID.

I've been playing around with both DifferenceKit and your library and I know the use cases of the two frameworks aren't exactly the same, but yours is more usable IMO. I've been enjoying it a lot.

**Comment by crabman448** [comment]
I support this idea `func isContentEqual(to:) -> Bool`.

I also have another thing to discuss. As I understood today `TableSection` uniqueness is based on the 
```
/// Unique identifier of the section
public let UUID: String = NSUUID().uuidString
```
Do you think it is the best approach? Or maybe it is better to somehow calculate it based on section content? Or maybe externalise it out of the library to the users of the library?

**Comment by crabman448** [comment]
I think `func isContentEqual(to:) -> Bool` can fit better than `modelID`

**Comment by crabman448** [comment]
Am I right, that this 
```
director?.section(at: indexPath.section)?.remove(at: indexPath.item)
tableView.deleteRows(at: [indexPath], with: .automatic)
```
should be equal to
```
director?.reloadData(after: { director in
    director.section(at: indexPath.section)?.remove(at: indexPath.item)
    return TableReloadAnimations.default()
}, onEnd: nil)
```

**Comment by malcommac** [comment]
There is something I'm missing; `modelID` is used to compare two models and see what's changed in a section (removed/moved/added items).
The stuff you are proposing is to use a `func isContentEqual(to:) -> Bool` instead (and remove the `modelID` right? I think it does not make sense anymore with this function)

**Comment by crabman448** [comment]
The thing with modelID is that its type is `Int`.
For example all my objects' ids are `String`, that means if I want to conform to `ModelProtocol` I need to do this
```
let objectId: String
var modelID: Int {
    return objectId.hashValue
}
```
But we can't rely on `hashValue` as on unique identifier as hash collisions could happen

Instead of
```
modelID: Int
```
We can add this function
```
// This one can be used instead of modelID
func sameModel(to: ) -> Bool
```
And even more:
```
// This one can probably be used by director 
// to reload specific cells if content changed 
// Can be optional I think
func isContentEqual(to: ) -> Bool
```

**Comment by malcommac** [comment]
Hi, I'm back after several months. I've rewritten several part of the framework including the diff algorithm which is now based upon DifferenceKit project.
I've moved it a new name, OwlKit - https://github.com/malcommac/Owl.
I'll be more than happy to listen your opinions. I'll do my best to release an official version in two weeks.

**Comment by wow-such-amazing** [comment]
Hi!
Thanks for your awesome work. I love FlowKit and sure that I will love OwlKit even more. Will have a look as soon as possible. 
And thank you again for this great work ❤️
