### ISSUE TITLE
Support for collapsible TableSection

### ISSUE THREAD

**Issue by marcmatta** [malcommac/FlowKit#7]
A real simple change to the TableSection could add an expandable UITableview sections behavior.

I've attached files which are edited to include this behavior and showcase in the Table sample section as well. 

Is it possible to merge these changes and update the library?

It would be way nicer to just use pods with these changes than to provide a workaround for the same behavior since the TableSection class is not declared as an open class making it impossible to sub-class and extend the library.

[Pached files.zip](https://github.com/malcommac/FlowKit/files/2137237/Pached.files.zip)

**Comment by marcmatta** [comment]
@malcommac can you please check the files and let me know if this will be feasible?

Thank you!

**Comment by malcommac** [comment]
Nice addition @marcmatta. I've just added it both in library and examples, scheduled for 0.6.0 milestone.
