### ISSUE TITLE
Silent update

### ISSUE THREAD

**Issue by crabman448** [malcommac/FlowKit#8]
Another suggestion 🙂 
Sometimes we can have favourite buttons inside cells. When we tap this button we have some animation. To have consistent table we need to update our dataSource. But I don't want to call reload data and brake the animation. I want to a silent update of the data source just to be sure, that UI and dataSource are the same. For this purpose it would be great to be able to do something like
`director?.silentUpdate(model: ModelProtocol, at indexPath: IndexPath)`

You did really great job for this library and documentation.

I currently implemented by using this 
`this.director?.section(at: 0)?.set(models: models)`
Without calling reload data. But it would be nice to update only one model this way

**Comment by malcommac** [comment]
I've added `set(model:at:)` function both for `TableSection` and `CollectionSection`.
It just replace an existing instance at given index with a new one (reload must be called manually as for other changes functions).

**Comment by crabman448** [comment]
Thanks! 👍

**Comment by crabman448** [comment]
Just missclicked the `comment` button
