### ISSUE TITLE
How to use to set checkmarks on cells?

### ISSUE THREAD

**Issue by cwoloszynski** [malcommac/FlowKit#9]
I am trying to initialize a table with the first row selected using FlowKit.  I cannot see how I should use this framework to do this.  I can see registering for callbacks to set the checkmarks on taps, but I don't see how to set the initial state of a selected row.

Any suggestions?

P.S.  This framework is GREAT.  I really appreciate the design and the work done to create it.  I hope I can contribute to it.

**Comment by malcommac** [comment]
Hi @cwoloszynski ; thank you.
Regards your question: you can use/set/unset default checkmarks on cell as you normally use it.
For example the following code set the checkmark (not toggle it) on cell's tap:

```swift
self.on.tap = { ctx in
	ctx.cell?.accessoryType = UITableViewCell.AccessoryType.checkmark
	return .deselectAnimated
}
```
